Module: LambdaSharpChallenge.PollyToS3Module
Version: 1.0-DEV
Description: Send text to Polly to save an audio file to S3
Items:
  
  - Resource: PollyPermissions
    Scope: PollyFunction
    Value: "*"
    Allow:
      - polly:DescribeVoices
      - polly:SynthesizeSpeech

  - Resource: ArticlesBucket
    Scope: PollyFunction
    Type: AWS::S3::Bucket
    Allow: ReadWrite

  - Function: PollyFunction
    Description: Endpoints to send text to Polly to save to a S3 bucket
    Memory: 512
    Timeout: 30
    Sources:
      - Api: POST:/articles
        Invoke: Logic::AddItem
